<?php
/**
 * Created by PhpStorm.
 * User: wg
 * Date: 23.06.16
 * Time: 23:11
 */

namespace modules\blog\controllers;

use modules\blog\models\Categories;
use modules\blog\models\Posts;
use system\Front;

/**
 * Class Blog
 * @package modules\blog\controllers
 */
class Blog extends Front
{
    private $posts;
    private $categories;

    public function __construct()
    {
        parent::__construct();

        $this->posts = new Posts('post');
        $this->categories = new Categories('posts_categories');
    }

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }

    public function categories()
    {
        return $this->categories->get();
    }

    public function posts()
    {
        return $this->posts->get();
    }

    public function tags()
    {
        return 'In progress';
    }
}