<?php
/**
 * Created by PhpStorm.
 * User: wg
 * Date: 16.06.16
 * Time: 20:59
 */

namespace system\components\contentTypes\models;

use system\models\Engine;

class ContentTypes extends Engine
{
    /**
     * @param $id
     * @param string $key
     * @return array|mixed
     */
    public function getData($id, $key= '*')
    {
        $d = self::$db->select("select {$key} from __content_types where id={$id} limit 1")->row($key);

        if($key != '*') return $d;

        if(isset($d['settings']) && !empty($d['settings'])) $d['settings'] = unserialize($d['settings']);


        if($d['parent_id'] > 0){
            $types_id = $d['parent_id'];
            $subtypes_id = $d['id'];
        } else {
            $types_id    = $d['id'];
            $subtypes_id = 0;
        }

        $d['features']     = $this->getSelectedFeatures($types_id, $subtypes_id);
        $d['images_sizes'] = $this->getSelectedImagesSizes($id);
//        echo $this->getErrorMessage();
        return $d;
    }

    private function getSelectedImagesSizes($types_id)
    {
        return self::$db
            ->select("select images_sizes_id from __content_types_images_sizes where types_id={$types_id}")
            ->all('images_sizes_id');
    }

    /**
     * @param $data
     * @return bool|string
     */
    public function create($data)
    {
        $s = parent::createRow('__content_types', $data);
        if($s>0 && $data['parent_id'] > 0){
            self::$db->update('__content_types', ['isfolder'=>1], "id={$data['parent_id']} limit 1");
        }
        if($s>0){
            // content_types_images_sizes
            $ct = $this->request->post('ct_images_sizes');
            if($ct){
                foreach ($ct as $k=>$sizes_id) {
                    $this->createRow('__content_types_images_sizes', ['types_id' => $s, 'images_sizes_id' => $sizes_id]);
                }
            }
        }
        return $s;
    }

    /**
     * @param $id
     * @param $data
     * @return bool
     */
    public function update($id, $data)
    {
        $s = parent::updateRow('__content_types', $id, $data);
        if($s>0){
            self::$db->delete("__content_types_images_sizes", "types_id = {$id}");
            // content_types_images_sizes
            $ct = $this->request->post('ct_images_sizes');
            if($ct){

                foreach ($ct as $k=>$sizes_id) {
                    $this->createRow('__content_types_images_sizes', ['types_id' => $id, 'images_sizes_id' => $sizes_id]);
                }
            }
        }
        return $s;
    }

    public function delete($id)
    {
        $data = $this->getData($id);

        $s = parent::deleteRow('__content_types', $id); // TODO: Change the autogenerated stub

        if($s > 0 && $data['parent_id'] > 0){
            if(! $this->hasChildren($data['parent_id'])){
                parent::updateRow('__content_types', $data['parent_id'], ['isfolder' => 0]);
            }
        }

        return $s;
    }

    public function hasChildren($id)
    {
        return self::$db
            ->select("select count(id) as t from __content_types where parent_id={$id}")
            ->row('t') > 0;
    }

    public function issetTemplate($parent_id, $type, $id = null)
    {
        $parent_id = (int)$parent_id;
        return self::$db->select("
            select id
            from __content_types
            where parent_id={$parent_id} and type='{$type}' ". ($id ? " and id <> $id" : '') ." limit 1")
            ->row('id');
    }

    public function getFeatures()
    {
        return self::$db
            ->select("
                select f.id, i.name
                from __features f, __features_info i
                where f.status='published' and f.parent_id=0 and i.features_id=f.id and i.languages_id={$this->languages_id}
            ")
            ->all();
    }

    /**
     * @param $types_id
     * @param $subtypes_id
     * @param $features_id
     * @return bool|string
     */
    public function selectFeatures($types_id, $subtypes_id, $features_id)
    {
        $is = self::$db->select("
                select id
                from __features_content
                where
                content_types_id    = {$types_id}    and
                content_subtypes_id = {$subtypes_id} and
                features_id         = {$features_id}
                 ")->row('id') > 0;

        if($is) return 0;

        $pos = self::$db->select("
                select MAX(position) as t
                from __features_content
                where
                content_types_id    = {$types_id} and
                content_subtypes_id = {$subtypes_id}
                 ")->row('t');

        return $this->createRow
        (
            '__features_content',
            [
                'content_types_id'    => $types_id,
                'content_subtypes_id' => $subtypes_id,
                'features_id'         => $features_id,
                'position'            => ++ $pos
            ]
        );
    }

    /**
     * @param $types_id
     * @param $subtypes_id
     * @return mixed
     */
    public function getSelectedFeatures($types_id, $subtypes_id)
    {
        return self::$db
            ->select("
                select fc.features_id as id, f.type, i.name
                from __features_content fc
                join __features f on f.id=fc.features_id
                join __features_info i on i.features_id=f.id and i.languages_id={$this->languages_id}
                where
                content_types_id    = {$types_id} and
                content_subtypes_id = {$subtypes_id}
                order by abs(fc.position) asc
                ")
            ->all();
    }

    public function deleteFeatures($id)
    {
        return $this->deleteRow('__features_content', $id);
    }

    public function getContentImagesSizes()
    {
        return self::$db->select("select * from __content_images_sizes order by id asc")->all();
    }


    public function getModules()
    {
        return self::$db->select("select controller from __modules")->all();
    }

    public function getFeaturesTypes()
    {
        return self::$db->enumValues('__features', 'type');
    }

    public function get($parent_id)
    {
        return self::$db->select("select id, name from __content_types where parent_id={$parent_id} order by id asc")->all();
    }
}