<?php

namespace modules\newsletter\controllers;

defined("CPATH") or die();
/**
 * Class Newsletter
 * @name Розсилка новин
 */
class Newsletter extends \system\Front
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}